##################################################################################
# Cloudify Fabric built in types and plugins definitions.
##################################################################################
plugins:
    fabric:
        executor: central_deployment_agent
        source: https://github.com/ICS-MU/westlife-cloudify-fabric-plugin/archive/1.5.1.1.zip
        package_name: cloudify-fabric-plugin
        package_version: '1.5.1.1'
